// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Stock Types
export const GET_STOCKS = 'GET_STOCKS';
export const GET_ALL_STOCKS = 'GET_ALL_STOCKS';
export const GET_STOCK_DETAIL = 'GET_STOCK_DETAIL';
export const GET_STOCK_BY_ID = 'GET_STOCK_BY_ID';
export const GET_TRENDING_STOCKS = 'GET_TRENDING_STOCKS';
export const GET_MARKET_INDICES = 'GET_MARKET_INDICES';
export const STOCKS_LOADING = 'STOCKS_LOADING';
export const STOCKS_ERROR = 'STOCKS_ERROR';
export const CLEAR_STOCK_DETAIL = 'CLEAR_STOCK_DETAIL';

// Portfolio Types
export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const GET_PORTFOLIO_SUMMARY = 'GET_PORTFOLIO_SUMMARY';
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';

// Transaction Types
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const BUY_STOCK = 'BUY_STOCK';
export const SELL_STOCK = 'SELL_STOCK';
export const GET_TRANSACTION_STATS = 'GET_TRANSACTION_STATS';
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';

// Watchlist Types
export const GET_WATCHLIST = 'GET_WATCHLIST';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const WATCHLIST_ERROR = 'WATCHLIST_ERROR';

// Alert Types
export const GET_ALERTS = 'GET_ALERTS';
export const CREATE_ALERT = 'CREATE_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';
export const GET_TRIGGERED_ALERTS = 'GET_TRIGGERED_ALERTS';
export const ALERTS_ERROR = 'ALERTS_ERROR';

// Achievement Types
export const GET_ALL_ACHIEVEMENTS = 'GET_ALL_ACHIEVEMENTS';
export const GET_USER_ACHIEVEMENTS = 'GET_USER_ACHIEVEMENTS';
export const CHECK_ACHIEVEMENTS = 'CHECK_ACHIEVEMENTS';
export const ACHIEVEMENTS_ERROR = 'ACHIEVEMENTS_ERROR';

// Recommendation Types
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';
export const GET_STOCK_RECOMMENDATION = 'GET_STOCK_RECOMMENDATION';
export const RECOMMENDATIONS_ERROR = 'RECOMMENDATIONS_ERROR';

// News Types
export const GET_NEWS = 'GET_NEWS';
export const GET_STOCK_SENTIMENT = 'GET_STOCK_SENTIMENT';
export const NEWS_ERROR = 'NEWS_ERROR';

// Analytics Types
export const GET_PORTFOLIO_ANALYTICS = 'GET_PORTFOLIO_ANALYTICS';
export const GET_RISK_METRICS = 'GET_RISK_METRICS';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR';